version: "3.3"

volumes:
  esdata:
    driver: local
  mesh-keystore:
    driver: local
  mesh-data:
    driver: local
  mesh-uploads:
    driver: local

services:
  cra-starter:
    build: ./home
    container_name: www-home
    ports:
      - "5000:8080"
    environment:
      BLOG_URL: http://www-blog:5100
      DEMO_URL: http://www-demo:5100

  nextjs-starter:
    build: ./demo
    container_name: www-demo
    ports:
      - "5100:8080"

  nextjs-starter-blog:
    build: ./blog
    container_name: www-blog
    ports:
      - "5200:8080"

  # mesh:
  #   image: gentics/mesh-demo:1.7.6
  #   container_name: mesh-server
  #   stop_grace_period: 5m
  #   environment:
  #     - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - MESH_ELASTICSEARCH_START_EMBEDDED=false
  #     - MESH_AUTH_KEYSTORE_PASS=changeme
  #     - MESH_MONITORING_HTTP_HOST=127.0.0.1
  #     - MESH_ELASTICSEARCH_COMPLIANCE_MODE=ES_7
  #     - MESH_INITIAL_ADMIN_PASSWORD=admin
  #   ports:
  #     - "8080:8080"
  #     - "127.0.0.1:8081:8081"

  #   volumes:
  #     - mesh-data:/graphdb
  #     - mesh-uploads:/uploads
  #     - mesh-keystore:/keystore

  #   ulimits:
  #     nofile:
  #       soft: 20000
  #       hard: 40000

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
  #   container_name: mesh-elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   stop_grace_period: 5m
  #   ports:
  #     - "127.0.0.1:9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #     memlock:
  #       soft: -1
  #       hard: -1
