version: '3.3'

services:
  demo:
    build: ./demo
    container_name: www-demo
    environment:
      BLOG_URL: http://www-blog:5200
    ports:
      - '5100:5100'

  blog:
    build: ./blog
    container_name: www-blog
    ports:
      - '5200:5200'
